import pdb
from models.team import Team
from models.player import Player
from models.match import Match

import repositories.match_repository as match_repository
import repositories.player_repository as player_repository
import repositories.team_repository as team_repository

match_repository.delete_all()
player_repository.delete_all()
team_repository.delete_all()

unattached = Team("Unattached", " ", " ", " ")
team_repository.save(unattached)

# Honda West

team_1 = Team("Colorado Avalanche", "Jared Bednar", "Pepsi Center", "Denver, CO")
team_repository.save(team_1)

player_1 = Player("Nathan", "MacKinnon", 25, team_1, "Center", 0)
player_repository.save(player_1)
player_2 = Player("Nazem", "Kadri", 30, team_1, "Center", 0)
player_repository.save(player_2)
player_3 = Player("Gabriel", "Landeskog", 28, team_1, "Left Wing", 0)
player_repository.save(player_3)
player_4 = Player("Andre", "Burakovsky", 26, team_1, "Left Wing", 0)
player_repository.save(player_4)
player_5 = Player("Mikko", "Rantanen", 24, team_1, "Right Wing", 0)
player_repository.save(player_5)
player_6 = Player("Joonas", "Donskoi", 29, team_1, "Right Wing", 0)
player_repository.save(player_6)
player_7 = Player("Erik", "Johnson", 33, team_1, "Defence", 0)
player_repository.save(player_7)
player_8 = Player("Cale", "Makar", 22, team_1, "Defence", 0)
player_repository.save(player_8)
player_9 = Player("Devon", "Toews", 27, team_1, "Defence", 0)
player_repository.save(player_9)
player_10 = Player("Samuel", "Girard", 22, team_1, "Defence", 0)
player_repository.save(player_10)
player_11 = Player("Phillip", "Grubauer", 29, team_1, "Goalkeeper", 0)
player_repository.save(player_11)
player_12 = Player("Pavel", "Francouz", 30, team_1, "Goalkeeper", 0)
player_repository.save(player_12)

team_2 = Team("Minnesota Wild", "Dean EVason", "Xcel Energy Center", "St. Paul, MN")
team_repository.save(team_2)

player_13 = Player("Joel", "Eriksson Ek", 24, team_2, "Center", 0)
player_repository.save(player_13)
player_14 = Player("Victor", "Rask", 28, team_2, "Center", 0)
player_repository.save(player_14)
player_15 = Player("Kirill", "Kaprizov", 23, team_2, "Left Wing", 0)
player_repository.save(player_15)
player_16 = Player("Zach", "Parise", 36, team_2, "Left Wing", 0)
player_repository.save(player_16)
player_17 = Player("Mats", "Zuccarello", 33, team_2, "Right Wing", 0)
player_repository.save(player_17)
player_18 = Player("Ryan", "Hartman", 26, team_2, "Right Wing", 0)
player_repository.save(player_18)
player_19 = Player("Jonas", "Brodin", 27, team_2, "Defence", 0)
player_repository.save(player_19)
player_20 = Player("Jared", "Spurgeon", 31, team_2, "Defence", 0)
player_repository.save(player_20)
player_21 = Player("Ryan", "Suter", 36, team_2, "Defence", 0)
player_repository.save(player_21)
player_22 = Player("Carson", "Soucy", 26, team_2, "Defence", 0)
player_repository.save(player_22)
player_23 = Player("Cam", "Talbot", 33, team_2, "Goalkeeper", 0)
player_repository.save(player_23)
player_24 = Player("Kaapo", "Kahkonen", 24, team_2, "Goalkeeper", 0)
player_repository.save(player_24)

team_3 = Team("St. Louis Blues", "Craig Berube", "Enterprise Center", "St. Louis, MO")
team_repository.save(team_3)

player_25 = Player("Ryan", "O'Reilly", 20, team_3, "Center", 0)
player_repository.save(player_25)
player_26 = Player("Brayden", "Schenn", 29, team_3, "Center", 0)
player_repository.save(player_26)
player_27 = Player("David", "Perron", 32, team_3, "Left Wing", 0)
player_repository.save(player_27)
player_28 = Player("Jaden", "Schwartz", 28, team_3, "Left Wing", 0)
player_repository.save(player_28)
player_29 = Player("Vladimir", "Tarasenko", 29, team_3, "Right Wing", 0)
player_repository.save(player_29)
player_30 = Player("Austin", "Poganski", 25, team_3, "Right Wing", 0)
player_repository.save(player_30)
player_31 = Player("Torey", "Krug", 30, team_3, "Defence", 0)
player_repository.save(player_31)
player_32 = Player("Vince", "Dunn", 24, team_3, "Defence", 0)
player_repository.save(player_32)
player_33 = Player("Marco", "Scandella", 31, team_3, "Defence", 0)
player_repository.save(player_33)
player_34 = Player("Robert", "Bortuzzo", 32, team_3, "Defence", 0)
player_repository.save(player_34)
player_35 = Player("Jordan", "Binnington", 27, team_3, "Goalkeeper", 0)
player_repository.save(player_35)
player_36 = Player("Ville", "Husso", 26, team_3, "Goalkeeper", 0)
player_repository.save(player_36)

team_4 = Team("Anaheim Ducks", "Dallas Eakins", "Honda Center", "Anaheim, CA")
team_repository.save(team_4)

player_37 = Player("Adam", "Henrique", 31, team_4, "Center", 0)
player_repository.save(player_37)
player_38 = Player("Ryan", "Getzlaf", 35, team_4, "Center", 0)
player_repository.save(player_38)
player_39 = Player("Max", "Comtois", 22, team_4, "Left Wing", 0)
player_repository.save(player_39)
player_40 = Player("Rickard", "Rakell", 27, team_4, "Left Wing", 0)
player_repository.save(player_40)
player_41 = Player("Jakob", "Silfverberg", 30, team_4, "Right Wing", 0)
player_repository.save(player_41)
player_42 = Player("Troy", "Terry", 23, team_4, "Right Wing", 0)
player_repository.save(player_42)
player_43 = Player("Cam", "Fowler", 29, team_4, "Defence", 0)
player_repository.save(player_43)
player_44 = Player("Kevin", "Shattenkirk", 32, team_4, "Defence", 0)
player_repository.save(player_44)
player_45 = Player("Josh", "Manson", 29, team_4, "Defence", 0)
player_repository.save(player_45)
player_46 = Player("Jamie", "Drysdale", 19, team_4, "Defence", 0)
player_repository.save(player_46)
player_47 = Player("John", "Gibson", 27, team_4, "Defence", 0)
player_repository.save(player_47)
player_48 = Player("Anthony", "Stolarz", 27, team_4, "Defence", 0)
player_repository.save(player_48)

# Discover Central

team_5 = Team("Carolina Hurricanes", "Rod Brind'Amour", "PNC Arena", "Raleigh, NC")
team_repository.save(team_5)

player_49 = Player("Sebastian", "Aho", 23, team_5, "Center", 0)
player_repository.save(player_49)
player_50 = Player("Vincent", "Trocheck", 27, team_5, "Center", 0)
player_repository.save(player_50)
player_51 = Player("Warren", "Foegele", 25, team_5, "Left Wing", 0)
player_repository.save(player_51)
player_52 = Player("Brock", "McGinn", 27, team_5, "Left Wing", 0)
player_repository.save(player_52)
player_53 = Player("Nino", "Niederreiter", 28, team_5, "Right Wing", 0)
player_repository.save(player_53)
player_54 = Player("Andrei", "Svechnikov", 21, team_5, "Right Wing", 0)
player_repository.save(player_54)
player_55 = Player("Dougie", "Hamilton", 27, team_5, "Defence", 0)
player_repository.save(player_55)
player_56 = Player("Brett", "Pesce", 26, team_5, "Defence", 0)
player_repository.save(player_56)
player_57 = Player("Jaccob", "Slavin", 26, team_5, "Defence", 0)
player_repository.save(player_57)
player_58 = Player("Brady", "Skjei", 27, team_5, "Defence", 0)
player_repository.save(player_58)
player_59 = Player("Petr", "Mrazek", 29, team_5, "Goalkeeper", 0)
player_repository.save(player_59)
player_60 = Player("Alex", "Nedeljkovic", 25, team_5, "Goalkeeper", 0)
player_repository.save(player_60)

team_6 = Team("Dallas Stars", "Rick Bowness", "American Airlines Center", "Dallas, TX")
team_repository.save(team_6)

player_61 = Player("Joe", "Pavelski", 36, team_6, "Center", 0)
player_repository.save(player_61)
player_62 = Player("Radek", "Faksa", 27, team_6, "Center", 0)
player_repository.save(player_62)
player_63 = Player("Roope", "Hintz", 24, team_6, "Left Wing", 0)
player_repository.save(player_63)
player_64 = Player("Jason", "Robertson", 21, team_6, "Left Wing", 0)
player_repository.save(player_64)
player_65 = Player("Denis", "Gurianov", 23, team_6, "Right Wing", 0)
player_repository.save(player_65)
player_66 = Player("Alexander", "Radulov", 34, team_6, "Right Wing", 0)
player_repository.save(player_66)
player_67 = Player("John", "Klingberg", 28, team_6, "Defence", 0)
player_repository.save(player_67)
player_68 = Player("Miro", "Heiskanen", 21, team_6, "Defence", 0)
player_repository.save(player_68)
player_69 = Player("Esa", "Lindell", 26, team_6, "Defence", 0)
player_repository.save(player_69)
player_70 = Player("Sami", "Vatanen", 29, team_6, "Defence", 0)
player_repository.save(player_70)
player_71 = Player("Anton", "Khudobin", 34, team_6, "Goalkeeper", 0)
player_repository.save(player_71)
player_72 = Player("Jake", "Oettinger", 22, team_6, "Goalkeeper", 0)
player_repository.save(player_72)

team_7 = Team("Chicago Blackhawks", "Jeremy Colliton", "United Center", "Chicago, IL")
team_repository.save(team_7)

player_73 = Player("Pius", "Suter", 24, team_7, "Center", 0)
player_repository.save(player_73)
player_74 = Player("Philipp", "Kurashev", 21, team_7, "Center", 0)
player_repository.save(player_74)
player_75 = Player("Dominik", "Kubalik", 25, team_7, "Left Wing", 0)
player_repository.save(player_75)
player_76 = Player("Brandon", "Hagel", 22, team_7, "Left Wing", 0)
player_repository.save(player_76)
player_77 = Player("Patrick", "Kane", 32, team_7, "Right Wing", 0)
player_repository.save(player_77)
player_78 = Player("Andrew", "Shaw", 29, team_7, "Right Wing", 0)
player_repository.save(player_78)
player_79 = Player("Adam", "Boqvist", 20, team_7, "Defence", 0)
player_repository.save(player_79)
player_80 = Player("Duncan", "Keith", 37, team_7, "Defence", 0)
player_repository.save(player_80)
player_81 = Player("Calvin", "De Haan", 29, team_7, "Defence", 0)
player_repository.save(player_81)
player_82 = Player("Nikita", "Zadorov", 26, team_7, "Defence", 0)
player_repository.save(player_82)
player_83 = Player("Malcolm", "Subban", 27, team_7, "Goalkeeper", 0)
player_repository.save(player_83)
player_84 = Player("Kevin", "Lankinen", 25, team_7, "Goalkeeper", 0)
player_repository.save(player_84)

team_8 = Team("Detroit Red Wings", "Jeff Blashill", "Little Caesars Arena", "Detroit, MI")
team_repository.save(team_8)

player_85 = Player("Dylan", "Larkin", 24, team_8, "Center", 0)
player_repository.save(player_85)
player_86 = Player("Robby", "Fabbri", 25, team_8, "Center", 0)
player_repository.save(player_86)
player_87 = Player("Jakub", "Vrana", 25, team_8, "Left Wing", 0)
player_repository.save(player_87)
player_88 = Player("Adam", "Erne", 26, team_8, "Left Wing", 0)
player_repository.save(player_88)
player_89 = Player("Filip", "Zadina", 21, team_8, "Right Wing", 0)
player_repository.save(player_89)
player_90 = Player("Bobby", "Ryan", 34, team_8, "Right Wing", 0)
player_repository.save(player_90)
player_91 = Player("Filip", "Hronek", 23, team_8, "Defence", 0)
player_repository.save(player_91)
player_92 = Player("Marc", "Staal", 34, team_8, "Defence", 0)
player_repository.save(player_92)
player_93 = Player("Danny", "DeKeyser", 31, team_8, "Defence", 0)
player_repository.save(player_93)
player_94 = Player("Christian", "Djoos", 26, team_8, "Defence", 0)
player_repository.save(player_94)
player_95 = Player("Calvin", "Pickard", 29, team_8, "Goalkeeper", 0)
player_repository.save(player_95)
player_96 = Player("Jonathan", "Bernier", 32, team_8, "Goalkeeper", 0)
player_repository.save(player_96)

# MassMutual East

team_9 = Team("Washington Capitals", "Peter Laviolette", "Capital One Arena", "Washington, DC")
team_repository.save(team_9)

player_97 = Player("Nicklas", "Backstrom", 33, team_9, "Center", 0)
player_repository.save(player_97)
player_98 = Player("Evgeny", "Kuznetsov", 28, team_9, "Center", 0)
player_repository.save(player_98)
player_99 = Player("Alex", "Ovechkin", 35, team_9, "Left Wing", 0)
player_repository.save(player_99)
player_100 = Player("Conor", "Sheary", 28, team_9, "Left Wing", 0)
player_repository.save(player_100)
player_101 = Player("T.J.", "Oshie", 34, team_9, "Right Wing", 0)
player_repository.save(player_101)
player_102 = Player("Tom", "Wilson", 27, team_9, "Right Wing", 0)
player_repository.save(player_102)
player_103 = Player("John", "Carlson", 31, team_9, "Defence", 0)
player_repository.save(player_103)
player_104 = Player("Justin", "Schultz", 30, team_9, "Defence", 0)
player_repository.save(player_104)
player_105 = Player("Brenden", "Dillon", 30, team_9, "Defence", 0)
player_repository.save(player_105)
player_106 = Player("Zdeno", "Chara", 44, team_9, "Defence", 0)
player_repository.save(player_106)
player_107 = Player("Ilya", "Samsonov", 24, team_9, "Goalkeeper", 0)
player_repository.save(player_107)
player_108 = Player("Vitek", "Vanecek", 25, team_9, "Goalkeeper", 0)
player_repository.save(player_108)

team_10 = Team("Boston Bruins", "Bruce Cassidy", "TD Garden", "Boston, MA")
team_repository.save(team_10)

player_109 = Player("Patrice", "Bergeron", 35, team_10, "Center", 0)
player_repository.save(player_109)
player_110 = Player("David", "Krejci", 34, team_10, "Center", 0)
player_repository.save(player_110)
player_111 = Player("Brad", "Marchand", 32, team_10, "Left Wing", 0)
player_repository.save(player_111)
player_112 = Player("Taylor", "Hall", 29, team_10, "Left Wing", 0)
player_repository.save(player_112)
player_113 = Player("David", "Pastrnak", 24, team_10, "Right Wing", 0)
player_repository.save(player_113)
player_114 = Player("Chris", "Wagner", 29, team_10, "Right Wing", 0)
player_repository.save(player_114)
player_115 = Player("Charlie", "McAvoy", 23, team_10, "Defence", 0)
player_repository.save(player_115)
player_116 = Player("Mike", "Reilly", 27, team_10, "Defence", 0)
player_repository.save(player_116)
player_117 = Player("Matt", "Grzelcyk", 27, team_10, "Defence", 0)
player_repository.save(player_117)
player_118 = Player("Jakub", "Zboril", 24, team_10, "Defence", 0)
player_repository.save(player_118)
player_119 = Player("Tuukka", "Rask", 34, team_10, "Goalkeeper", 0)
player_repository.save(player_119)
player_120 = Player("Jaroslav", "Halak", 35, team_10, "Goalkeeper", 0)
player_repository.save(player_120)

team_11 = Team("New York Rangers", "David Quinn", "Madison Square Garden", "Ney York, NY")
team_repository.save(team_11)

player_121 = Player("Ryan", "Strome", 27, team_11, "Center", 0)
player_repository.save(player_121)
player_122 = Player("Mika", "Zibanejad", 28, team_11, "Center", 0)
player_repository.save(player_122)
player_123 = Player("Artemi", "Panarin", 29, team_11, "Left Wing", 0)
player_repository.save(player_123)
player_124 = Player("Chris", "Kreider", 29, team_11, "Left Wing", 0)
player_repository.save(player_124)
player_125 = Player("Pavel", "Buchnevich", 26, team_11, "Right Wing", 0)
player_repository.save(player_125)
player_126 = Player("Kaapo", "Kakko", 20, team_11, "Right Wing", 0)
player_repository.save(player_126)
player_127 = Player("Adam", "Fox", 23, team_11, "Defence", 0)
player_repository.save(player_127)
player_128 = Player("Ryan", "Lindgren", 23, team_11, "Defence", 0)
player_repository.save(player_128)
player_129 = Player("K'Andre", "Miller", 21, team_11, "Defence", 0)
player_repository.save(player_129)
player_130 = Player("Brendan", "Smith", 32, team_11, "Defence", 0)
player_repository.save(player_130)
player_131 = Player("Igor", "Shesterkin", 25, team_11, "Goalkeeper", 0)
player_repository.save(player_131)
player_132 = Player("Alexandar", "Georgiev", 25, team_11, "Goalkeeper", 0)
player_repository.save(player_132)

team_12 = Team("Philadelphia Flyers", "Alain Vigneault", "Wells Fargo Center", "Philadelphia, PA")
team_repository.save(team_12)

player_133 = Player("Claude", "Giroux", 33, team_12, "Center", 0)
player_repository.save(player_133)
player_134 = Player("Sean", "Couturier", 28, team_12, "Center", 0)
player_repository.save(player_134)
player_135 = Player("James", "Van Riemsdyk", 31, team_12, "Left Wing", 0)
player_repository.save(player_135)
player_136 = Player("Joel", "Farabee", 21, team_12, "Left Wing", 0)
player_repository.save(player_136)
player_137 = Player("Jakub", "Voracek", 31, team_12, "Right Wing", 0)
player_repository.save(player_137)
player_138 = Player("Travis", "Konecny", 24, team_12, "Right Wing", 0)
player_repository.save(player_138)
player_139 = Player("Ivan", "Provorov", 24, team_12, "Defence", 0)
player_repository.save(player_139)
player_140 = Player("Shayne", "Gostisbehere", 28, team_12, "Defence", 0)
player_repository.save(player_140)
player_141 = Player("Philippe", "Myers", 24, team_12, "Defence", 0)
player_repository.save(player_141)
player_142 = Player("Robert", "Hagg", 26, team_12, "Defence", 0)
player_repository.save(player_142)
player_143 = Player("Brian", "Elliott", 36, team_12, "Goalkeeper", 0)
player_repository.save(player_143)
player_144 = Player("Carter", "Hart", 22, team_12, "Goalkeeper", 0)
player_repository.save(player_144)

# Scotia North

team_13 = Team("Toronto Maple Leafs", "Sheldon Keefe", "Scotiabank Arena", "Toronto, ON")
team_repository.save(team_13)

player_145 = Player("Auston", "Matthews", 23, team_13, "Center", 0)
player_repository.save(player_145)
player_146 = Player("John", "Tavares", 30, team_13, "Center", 0)
player_repository.save(player_146)
player_147 = Player("Zach", "Hyman", 28, team_13, "Left Wing", 0)
player_repository.save(player_147)
player_148 = Player("Nick", "Foligno", 33, team_13, "Left Wing", 0)
player_repository.save(player_148)
player_149 = Player("Mitchell", "Marner", 23, team_13, "Right Wing", 0)
player_repository.save(player_149)
player_150 = Player("William", "Nylander", 24, team_13, "Right Wing", 0)
player_repository.save(player_150)
player_151 = Player("Morgan", "Rielly", 27, team_13, "Defence", 0)
player_repository.save(player_151)
player_152 = Player("Jake", "Muzzin", 32, team_13, "Defence", 0)
player_repository.save(player_152)
player_153 = Player("TJ", "Brodie", 30, team_13, "Defence", 0)
player_repository.save(player_153)
player_154 = Player("Travis", "Dermott", 24, team_13, "Defence", 0)
player_repository.save(player_154)
player_155 = Player("Jack", "Campbell", 29, team_13, "Goalkeeper", 0)
player_repository.save(player_155)
player_156 = Player("Michael", "Hutchinson", 31, team_13, "Goalkeeper", 0)
player_repository.save(player_156)

team_14 = Team("Winnipeg Jets", "Paul Maurice", "Bell MTS Place", "Winnipeg, MB")
team_repository.save(team_14)

player_157 = Player("Mark", "Scheifele", 28, team_14, "Center", 0)
player_repository.save(player_157)
player_158 = Player("Andrew", "Copp", 26, team_14, "Center", 0)
player_repository.save(player_158)
player_159 = Player("Nikolaj", "Ehlers", 25, team_14, "Left Wing", 0)
player_repository.save(player_159)
player_160 = Player("Kyle", "Connor", 24, team_14, "Left Wing", 0)
player_repository.save(player_160)
player_161 = Player("Blake", "Wheeler", 34, team_14, "Right Wing", 0)
player_repository.save(player_161)
player_162 = Player("Pierre-Luc", "Dubois", 22, team_14, "Right Wing", 0)
player_repository.save(player_162)
player_163 = Player("Neal", "Pionk", 25, team_14, "Defence", 0)
player_repository.save(player_163)
player_164 = Player("Josh", "Morrissey", 26, team_14, "Defence", 0)
player_repository.save(player_164)
player_165 = Player("Derek", "Forbort", 29, team_14, "Defence", 0)
player_repository.save(player_165)
player_166 = Player("Jordie", "Benn", 33, team_14, "Defence", 0)
player_repository.save(player_166)
player_167 = Player("Laurent", "Brossoit", 28, team_14, "Goalkeeper", 0)
player_repository.save(player_167)
player_168 = Player("Connor", "Hellebuyck", 27, team_14, "Goalkeeper", 0)
player_repository.save(player_168)

team_15 = Team("Calgary Flames", "Darryl Sutter", "Scotiabank Saddledome", "Calgary, AB")
team_repository.save(team_15)

player_169 = Player("Elias", "Lindholm", 26, team_15, "Center", 0)
player_repository.save(player_169)
player_170 = Player("Sean", "Monahan", 26, team_15, "Center", 0)
player_repository.save(player_170)
player_171 = Player("Johnny", "Gaudreau", 27, team_15, "Left Wing", 0)
player_repository.save(player_171)
player_172 = Player("Matthew", "Tkachuk", 23, team_15, "Left Wing", 0)
player_repository.save(player_172)
player_173 = Player("Brett", "Ritchie", 27, team_15, "Right Wing", 0)
player_repository.save(player_173)
player_174 = Player("Buddy", "Robinson", 29, team_15, "Right Wing", 0)
player_repository.save(player_174)
player_175 = Player("Mark", "Giordano", 37, team_15, "Defence", 0)
player_repository.save(player_175)
player_176 = Player("Rasmus", "Andersson", 24, team_15, "Defence", 0)
player_repository.save(player_176)
player_177 = Player("Juuso", "Valimaki", 22, team_15, "Defence", 0)
player_repository.save(player_177)
player_178 = Player("Christopher", "Tanev", 31, team_15, "Defence", 0)
player_repository.save(player_178)
player_179 = Player("Jacob", "Markstrom", 31, team_15, "Goalkeeper", 0)
player_repository.save(player_179)
player_180 = Player("Artyom", "Zagidulin", 25, team_15, "Goalkeeper", 0)
player_repository.save(player_180)

team_16 = Team("Vancouver Canucks", "Travis Green", "Rogers Arena", "Vancouver, BC")
team_repository.save(team_16)